changed react favicon
Binary-Cumates/T-Picker-Frontend pull request #18
Opened 2021-06-23 16:33 UTC by Utkarsh1504

issue #13

2021-06-23 18:52 UTC, iamdevvalecha commented
@Utkarsh1504 please share screenshot.

2021-06-23 18:55 UTC, iamdevvalecha requested changes
just change logo.

2021-06-23 19:13 UTC, Utkarsh1504 commented
Shall I have to design a logo for the favicon?

2021-06-23 21:08 UTC, iamdevvalecha commented
@Utkarsh1504 yes, we need t-picker favicon icon.

2021-06-24 06:00 UTC, Utkarsh1504 commented
favicon updated

**Favicon preview**
![Screenshot (27)](https://user-images.githubusercontent.com/76392681/123210364-8212d580-d4df-11eb-99b7-03e131fe4e57.png)

**preview in browser**
![Screenshot (28)](https://user-images.githubusercontent.com/76392681/123210405-9525a580-d4df-11eb-9c74-c63990527e5a.png)

2021-06-24 07:58 UTC, iamdevvalecha requested changes

2021-06-24 07:58 UTC, iamdevvalecha commented on public/index.html
> +  <!--
LGTM! but why extra line. and don't change indentation.

2021-06-24 07:58 UTC, iamdevvalecha commented on public/index.html
> +  <!--
indentation

2021-06-24 07:58 UTC, iamdevvalecha commented on public/index.html
> +</html>
remove extra line and fix indent.

2021-06-24 08:00 UTC, iamdevvalecha commented
just update favicon don't change anything. thank you.

2021-06-24 08:07 UTC, Utkarsh1504 commented
may be indentation changed due to my vscode setting. Okay i will fix it

2021-06-24 08:11 UTC, iamdevvalecha commented
> may be indentation changed due to my vscode setting. Okay i will fix it

just change favicon. nothing else.

2021-06-24 08:12 UTC, Utkarsh1504 commented
ok fixed now

2021-06-24 08:15 UTC, merged

2021-06-24 08:15 UTC, iamdevvalecha commented
@Utkarsh1504 thank you!